maintainer: Dhanoop Karunakaran
debug: True
train:
  lr: 0.0001
  gamma: 0.99
  betas:
    - 0.9
    - 0.999
  random_seed: 543
  n_epidode: 5000
  n_timesteps: 2000
  clip_param: 0.2
  update_freq: 4 # 2nd episode
  store_plotting_data: 5